services:
  app:
    build: .
    volumes:
      - .:/app
      - static-data:/app/staticfiles
      - media-data:/app/media
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-data:/app/staticfiles
      - media-data:/app/media
      - /etc/letsencrypt/archive/biotekpharm.uz/fullchain2.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/archive/biotekpharm.uz/privkey2.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-data:
  media-data: