services:
  biotekt-app:
    build: .
    volumes:
      - .:/app
      - biotekt-static:/app/staticfiles  # Statik fayllar uchun
      - biotekt-media:/app/media  # Media fayllar uchun
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - biotekt-network

  bekendchi-nginx:
    image: nginx:latest
    ports:
      - "7000:7000"  # HTTP uchun 7000-port
      - "8000:8000"  # HTTPS uchun 8443-port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - biotekt-static:/app/staticfiles  # Statik fayllar
      - biotekt-media:/app/media  # Media fayllar
      - /etc/letsencrypt:/etc/letsencrypt:ro  # SSL sertifikat fayllari
    depends_on:
      - biotekt-app
    networks:
      - biotekt-network

networks:
  bekendchi-network:
    driver: bridge

volumes:
  bekendchi-static:
  bekendchi-media: