# Generated by Django 5.2.4 on 2025-09-21 09:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overline_uz', models.CharField(default='Kompaniya haqida', max_length=80)),
                ('overline_ru', models.CharField(blank=True, default='', max_length=80)),
                ('overline_en', models.CharField(blank=True, default='', max_length=80)),
                ('title_line1_uz', models.CharField(default='BIOTEKPHARM – bu xalqaro farmatsevtika mahsulotlarini', max_length=200)),
                ('title_line1_ru', models.CharField(blank=True, default='', max_length=200)),
                ('title_line1_en', models.CharField(blank=True, default='', max_length=200)),
                ('title_line2_uz', models.CharField(default='yetkazib berish sohasida ishonchli hamkor', max_length=200)),
                ('title_line2_ru', models.CharField(blank=True, default='', max_length=200)),
                ('title_line2_en', models.CharField(blank=True, default='', max_length=200)),
                ('intro_uz', models.TextField(blank=True, default='')),
                ('intro_ru', models.TextField(blank=True, default='')),
                ('intro_en', models.TextField(blank=True, default='')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=app.models.upload_about)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About (Hero) bo‘limi',
                'verbose_name_plural': 'About (Hero) bo‘limi',
            },
        ),
        migrations.CreateModel(
            name='CompanyIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(default='BIOTEK PHARM haqida', max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kompaniya intro',
                'verbose_name_plural': 'Kompaniya intro',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, default='', max_length=120)),
                ('title_en', models.CharField(blank=True, default='', max_length=120)),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField(blank=True, default='')),
                ('text_en', models.TextField(blank=True, default='')),
                ('icon_type', models.CharField(choices=[('fa', 'Font Awesome class'), ('img', 'Image/SVG upload')], default='fa', max_length=3)),
                ('fa_class', models.CharField(blank=True, help_text="Masalan: 'fas fa-bullseye'", max_length=64)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='feature_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Sarlavha (EN)')),
                ('subtitle_uz', models.TextField(blank=True, default='', verbose_name='Quyi matn (UZ)')),
                ('subtitle_ru', models.TextField(blank=True, default='', verbose_name='Quyi matn (RU)')),
                ('subtitle_en', models.TextField(blank=True, default='', verbose_name='Quyi matn (EN)')),
                ('background', models.ImageField(upload_to='hero/', verbose_name='Fon rasmi')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero bo‘limi',
                'verbose_name_plural': 'Hero bo‘limi',
            },
        ),
        migrations.CreateModel(
            name='HistoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort tartibi')),
                ('year', models.CharField(blank=True, help_text='Masalan: 2005-yil', max_length=32)),
                ('title_uz', models.CharField(max_length=250)),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('title_en', models.CharField(blank=True, max_length=250, null=True)),
                ('text_uz', models.TextField(blank=True, null=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('icon_type', models.CharField(choices=[('fa', 'Font Awesome class'), ('img', 'Image file')], default='fa', max_length=3)),
                ('fa_class', models.CharField(blank=True, help_text='fa-solid fa-hospital-alt', max_length=100, null=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='history/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarix kartasi',
                'verbose_name_plural': 'Tarix kartalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Ko‘rsatish/berkitish')),
                ('order', models.PositiveIntegerField(default=1, help_text='Tartib raqami (1,2,3...) — kichik raqam oldin chiqadi')),
                ('name_uz', models.CharField(max_length=120, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=120, verbose_name='Nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Nomi (EN)')),
                ('logo', models.ImageField(help_text='Hamkor logotipi (SVG yoki PNG, eng yaxshi: 320×160, fon shaffof).', upload_to='partners/logos/')),
                ('url', models.URLField(blank=True, help_text='Hamkor vebsayti (ixtiyoriy). http(s) bilan.', verbose_name='Havola')),
                ('note_uz', models.CharField(blank=True, help_text='Ixtiyoriy qisqa izoh', max_length=160)),
                ('note_ru', models.CharField(blank=True, max_length=160)),
                ('note_en', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Ko‘rsatish/berkitish')),
                ('order', models.PositiveIntegerField(default=1, help_text='Tartib raqami (1,2,3...) — kichik raqam oldin chiqadi')),
                ('title_uz', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('text_uz', models.CharField(blank=True, max_length=250)),
                ('text_ru', models.CharField(blank=True, max_length=250)),
                ('text_en', models.CharField(blank=True, max_length=250)),
                ('icon_type', models.CharField(choices=[('fa', 'Font Awesome class orqali'), ('img', 'Rasm (PNG/SVG) orqali')], default='fa', help_text='Belgi qaysi ko‘rinishda bo‘lsin', max_length=3)),
                ('fa_class', models.CharField(blank=True, help_text='Masalan: <b>fa-solid fa-truck</b> yoki <b>fas fa-warehouse</b>. Agar rasm ishlatsangiz — bo‘sh qoldiring.', max_length=80)),
                ('icon_image', models.ImageField(blank=True, help_text='PNG/SVG 256×256 atrofida, fon shaffof bo‘lsa yaxshi.', null=True, upload_to='services/icons/')),
            ],
            options={
                'verbose_name': 'Xizmat kartkasi',
                'verbose_name_plural': 'Xizmat kartkalari',
                'ordering': ('order',),
            },
        ),
    ]
