# Generated by Django 5.2.4 on 2025-09-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'Biz haqimizda', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='featurecard',
            options={'ordering': ['order'], 'verbose_name': 'Afzallik kartochkasi', 'verbose_name_plural': 'Afzallik kartochkalari'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Bosh sahifa ', 'verbose_name_plural': 'Bosh sahifa '},
        ),
        migrations.AlterModelOptions(
            name='historycard',
            options={'ordering': ['order'], 'verbose_name': ' Bizning Tarix ', 'verbose_name_plural': 'Bizing Tarix '},
        ),
        migrations.AlterModelOptions(
            name='partnercard',
            options={'ordering': ('order',), 'verbose_name': 'Hamkorlar', 'verbose_name_plural': 'Hamkorlarlar'},
        ),
        migrations.AlterModelOptions(
            name='servicecard',
            options={'ordering': ('order',), 'verbose_name': 'Bizning Xizmatlar ', 'verbose_name_plural': 'Bizing Xizmatlar'},
        ),
    ]
