# Generated by Django 5.2.4 on 2025-10-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_aboutsection_options_alter_featurecard_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('samarkand', 'Samarqand'), ('tashkent', 'Toshkent'), ('khorezm', 'Xorazm'), ('ferghana', 'Farg‘ona')], max_length=20, unique=True, verbose_name='Hudud')),
                ('name_uz', models.CharField(blank=True, max_length=120, verbose_name='Nom (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=120, verbose_name='Nom (RU)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Nom (EN)')),
                ('address_uz', models.CharField(blank=True, max_length=255, verbose_name='Manzil (UZ)')),
                ('address_ru', models.CharField(blank=True, max_length=255, verbose_name='Manzil (RU)')),
                ('address_en', models.CharField(blank=True, max_length=255, verbose_name='Manzil (EN)')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('time_uz', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti (UZ)')),
                ('time_ru', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti (RU)')),
                ('time_en', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Joylashuv',
                'verbose_name_plural': 'Joylashuvlar',
                'ordering': ('region',),
            },
        ),
    ]
