# Generated by Django 5.2.4 on 2025-09-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_herosection_delete_product_delete_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, default='', max_length=120)),
                ('title_en', models.CharField(blank=True, default='', max_length=120)),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField(blank=True, default='')),
                ('text_en', models.TextField(blank=True, default='')),
                ('icon_type', models.CharField(choices=[('fa', 'Font Awesome class'), ('img', 'Image/SVG upload')], default='fa', max_length=3)),
                ('fa_class', models.CharField(blank=True, help_text="Masalan: 'fas fa-bullseye'", max_length=64)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='feature_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
