# Generated by Django 5.2.4 on 2025-09-08 06:59

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_featurecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overline_uz', models.CharField(default='Kompaniya haqida', max_length=80)),
                ('overline_ru', models.CharField(blank=True, default='', max_length=80)),
                ('overline_en', models.CharField(blank=True, default='', max_length=80)),
                ('title_line1_uz', models.CharField(default='BIOTEKPHARM – bu xalqaro farmatsevtika mahsulotlarini', max_length=200)),
                ('title_line1_ru', models.CharField(blank=True, default='', max_length=200)),
                ('title_line1_en', models.CharField(blank=True, default='', max_length=200)),
                ('title_line2_uz', models.CharField(default='yetkazib berish sohasida ishonchli hamkor', max_length=200)),
                ('title_line2_ru', models.CharField(blank=True, default='', max_length=200)),
                ('title_line2_en', models.CharField(blank=True, default='', max_length=200)),
                ('intro_uz', models.TextField(blank=True, default='')),
                ('intro_ru', models.TextField(blank=True, default='')),
                ('intro_en', models.TextField(blank=True, default='')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=app.models.upload_about)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About (Hero) bo‘limi',
                'verbose_name_plural': 'About (Hero) bo‘limi',
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Masalan: 2005-yil / 2012-yil / Bugun', max_length=20)),
                ('title_uz', models.CharField(max_length=180)),
                ('title_ru', models.CharField(blank=True, default='', max_length=180)),
                ('title_en', models.CharField(blank=True, default='', max_length=180)),
                ('text_uz', models.TextField(blank=True, default='')),
                ('text_ru', models.TextField(blank=True, default='')),
                ('text_en', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=app.models.upload_timeline)),
                ('icon_type', models.CharField(choices=[('fa', 'Font Awesome class'), ('img', 'Image/SVG upload')], default='fa', max_length=3)),
                ('fa_class', models.CharField(blank=True, help_text="Masalan: 'fa-solid fa-store' yoki 'fas fa-box-open'", max_length=64)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='timeline/icons/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Kartalar tartibi (kichik – birinchi)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Timeline (tarix) elementi',
                'verbose_name_plural': 'Timeline (tarix) elementlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
