# Generated by Django 5.2.4 on 2025-09-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_aboutsection_timelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(default='BIOTEK PHARM haqida', max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kompaniya intro',
                'verbose_name_plural': 'Kompaniya intro',
            },
        ),
        migrations.CreateModel(
            name='HistoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort tartibi')),
                ('year', models.CharField(blank=True, help_text='Masalan: 2005-yil', max_length=32)),
                ('title_uz', models.CharField(max_length=250)),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('title_en', models.CharField(blank=True, max_length=250, null=True)),
                ('text_uz', models.TextField(blank=True, null=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('icon_type', models.CharField(choices=[('fa', 'Font Awesome class'), ('img', 'Image file')], default='fa', max_length=3)),
                ('fa_class', models.CharField(blank=True, help_text='fa-solid fa-hospital-alt', max_length=100, null=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='history/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarix kartasi',
                'verbose_name_plural': 'Tarix kartalari',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='TimelineItem',
        ),
    ]
