# Generated by Django 5.2.4 on 2025-09-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_companyintro_historycard_delete_timelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Ko‘rsatish/berkitish')),
                ('order', models.PositiveIntegerField(default=1, help_text='Tartib raqami (1,2,3...) — kichik raqam oldin chiqadi')),
                ('name_uz', models.CharField(max_length=120, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=120, verbose_name='Nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Nomi (EN)')),
                ('logo', models.ImageField(help_text='Hamkor logotipi (SVG yoki PNG, eng yaxshi: 320×160, fon shaffof).', upload_to='partners/logos/')),
                ('url', models.URLField(blank=True, help_text='Hamkor vebsayti (ixtiyoriy). http(s) bilan.', verbose_name='Havola')),
                ('note_uz', models.CharField(blank=True, help_text='Ixtiyoriy qisqa izoh', max_length=160)),
                ('note_ru', models.CharField(blank=True, max_length=160)),
                ('note_en', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Ko‘rsatish/berkitish')),
                ('order', models.PositiveIntegerField(default=1, help_text='Tartib raqami (1,2,3...) — kichik raqam oldin chiqadi')),
                ('title_uz', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('text_uz', models.CharField(blank=True, max_length=250)),
                ('text_ru', models.CharField(blank=True, max_length=250)),
                ('text_en', models.CharField(blank=True, max_length=250)),
                ('icon_type', models.CharField(choices=[('fa', 'Font Awesome class orqali'), ('img', 'Rasm (PNG/SVG) orqali')], default='fa', help_text='Belgi qaysi ko‘rinishda bo‘lsin', max_length=3)),
                ('fa_class', models.CharField(blank=True, help_text='Masalan: <b>fa-solid fa-truck</b> yoki <b>fas fa-warehouse</b>. Agar rasm ishlatsangiz — bo‘sh qoldiring.', max_length=80)),
                ('icon_image', models.ImageField(blank=True, help_text='PNG/SVG 256×256 atrofida, fon shaffof bo‘lsa yaxshi.', null=True, upload_to='services/icons/')),
            ],
            options={
                'verbose_name': 'Xizmat kartkasi',
                'verbose_name_plural': 'Xizmat kartkalari',
                'ordering': ('order',),
            },
        ),
    ]
